AWSTemplateFormatVersion: 2010-09-09
Desciption: Cloud formation stack for ES, S3 and Lambda
Resources:
  ES:
    Type: "AWS::Elasticsearch::Domain"
    Properties:
      DomainName: "CFphotos"
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: "arn:aws:es:us-east-1:418888549033:domain/CFphotos/*"
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: "false"
        InstanceCount: "1"
        ZoneAwarenessEnabled: "false"
        InstanceType: "t2.small.elasticsearch"
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: "gp2"
      ElasticsearchVersion: "7.1"